### ISSUE TITLE
Contest winners are grouped by fish category not fish length

### ISSUE THREAD

**Issue by cobrex1** [piratjsk/Rby#5]
Firstly, thanks for updating to 1.13, appreciated.

When running the fishing contest, if two players catch the legendary pygmy whale, only the player with the largest whale comes first, and the second biggest does not appear in the winners list. The 2nd place person is the winner in the legendary group, or whichever is the next group winner. Had 20 players fishing, and only two appears in the winning list. 

I am not an experienced coder, however, could the placing be (or can they be set in the config) to only go by fish length?

**Comment by piratjsk** [comment]
As far as I know it already should go only by length.
Right now I don't have time, but on the weekend I will look into it and apply necessary fixes.
In the meantime you can check [fork by klugemonkey](https://www.spigotmc.org/threads/morefish-improved-fishing-and-fishing-competition.145753/page-20#post-3199390) which is also updated to 1.13.

**Comment by cobrex1** [comment]
Totally understand about time, so no issue there. It appears that the placing in the contest is affected by the ordinal grouping, which overrides the size of the fish, or only counts the 1st place placings in each fish category. I'll let you have a look at it at the weekend.

**Comment by piratjsk** [comment]
Over month late but this issue should be fixed now in [v2.2.2](https://github.com/piratjsk/Rby/releases/tag/mf-v2.2.2).
